### ISSUE TITLE
Support for multiple line groups in a template

### ISSUE THREAD

**Issue by rseabrook** [invoice-x/invoice2data#186]
It would be useful to be able to parse multiple sections with the `lines` plugin. An example where this would be useful is a credit card processing statement. An example statement can be found [here](https://content.heropay.com/wp-content/uploads/2016/11/Merchant-Services.jpg). It would be ideal to parse the "Plan Summary", "Deposits", and "Fees" sections into their own keys in the output.

**Comment by adrienjacob** [comment]
I agree, would be very heplful indeed. I understand this is related to issue https://github.com/invoice-x/invoice2data/issues/224 and PR https://github.com/invoice-x/invoice2data/pull/225

**Comment by rmilecki** [comment]
That `Merchant-Services.jpg` you linked is not available anymore. Does https://github.com/invoice-x/invoice2data/pull/308 (that was merged 1,5 year ago) resolve this issue? You can now have
```
fields:
  plan:
    parser: lines
    start: ...
    end: ...
    line: ...
  deposits:
    parser: lines
    start: ...
    end: ...
    line: ...
  fees:
    parser: lines
    start: ...
    end: ...
    line: ...
```
