### ISSUE TITLE
No template for invoice

### ISSUE THREAD

**Issue by tanmaysri** [invoice-x/invoice2data#191]
I have installed invoice2data and created a template for a particular invoice. But still it says no template for the invoice.

I have attached the template and the pdf I am trying to convert.

[Invoice_Exp_Dec001_Veneklasen.pdf](https://github.com/invoice-x/invoice2data/files/2746612/Invoice_Exp_Dec001_Veneklasen.pdf)

Template code
```
issuer: Veneklasen
fields:
  amount: Total(\d+\.\d+)
  date: InvoiceDate:(\d{1,4}\-\d{1,2}\-\d{1,4})
  #invoice_number: InvoiceNo:(\W\w+)
  invoice_number: InvoiceNo:(\S+)
  order_id: OrderID:(\w{2}\d{16,18})
keywords:
- Veneklasen
- India
options:
  currency: INR
  remove_whitespace: true
```

Can anyone please help me on this?
