### ISSUE TITLE
MultiLine order items for Custom template

### ISSUE THREAD

**Issue by SumantHegde003** [invoice-x/invoice2data#219]
Hi All,

Can anybody help with me multiline order items in PDF.

Also attaching the PDF template for references.

[nature.PDF](https://github.com/invoice-x/invoice2data/files/3017424/nature.PDF)

Thanks.

**Comment by SumantHegde003** [comment]
I tried with Start Line and end Line Syntax, But it is not giving me expected pattern?

Guys  @m3nu @hbrunn  please help me to resolve this pattern.

**Comment by m3nu** [comment]
You should look at the debug output to see how the text comes out. Then tune it for the line plugin.

**Comment by rmilecki** [comment]
```
lines:
  parser: lines
  start: Article Description with Specs.*
  end: C.S.T.
  first_line: \s*(?P<sr>[\d]+)\s+(?P<article_number>.*)\s+/(?P<hsn>.*)\s+/(?P<ean_upc>.*)\s+(?P<uom>\w\w)\s+(?P<price1>\d+\.\d+)\s+(?P<price2>\d+\.\d+)\s+(?P<price3>\d+\.\d+)\s+(?P<price4>\d+\.\d+)
  line: \s+(?P<name>.+)\s+(?P<price5>\d+\.\d+)\s+(?P<price6>\d+\.\d+)\s+(?P<price7>\d+\.\d+)\s+(?P<price8>\d+\.\d+)
```
