### ISSUE TITLE
DateFormat dd/mm/yyyy

### ISSUE THREAD

**Issue by darknd** [invoice-x/invoice2data#251]
Hi,

I always get the date in the following format:

`'date': datetime.datetime(2019, 7, 31, 0, 0),`

My template looks like this:

```
issuer: {hidden_data_protection}
fields:
  date: \d{1,2}\/\d{1,2}\/\d{4}
  amount: (\d+\.\d{1,2})
  invoice_number: ([A-Z]{2}\/\d{0,4}\/\d{0,2})
keywords:
  - {hidden_data_protection}
options:
  date_formats:
    - '%d/%m/%Y'
  languages:
    - es
  decimal_separator: '.'
```

How can i get the date in dd/mm/YYYY format?

Thank you very much for your time,
