### ISSUE TITLE
Is there a way to parse multiple tables using "lines"

### ISSUE THREAD

**Issue by suprateekn** [invoice-x/invoice2data#296]
I am having 2 tables in a single page of the pdf and want to extract data from both of them. Can't use the "tables" plugin as can have only the first line of data using that.

As far as I can understand the "lines" block is treated as a dictionary. So multiple table parsing using "lines" is not possible. Is there an alternative?

**Comment by rmilecki** [comment]
I can implement this but I need `invoice2data` maintainers to help me to decide on YAML syntax for it. I have two suggestions.
@m3nu: can you comment on below ideas, please?

### Use extended `fields` syntax
In the #307 I suggested each `fields` entry to be an associative array. That would allow very clean support for requested feature (without breaking backward compatibility), consider:
```
fields:
  foo:
    static: 'Lorem ipsum'
  items:
    plugin: lines
    settings:
      start: ...
      end: ...
      line: ...
  rates:
    plugin: lines
    settings:
      start: ...
      end: ...
      line: ...
```
That would require rewriting plugins API a bit which I can easily handle. The only problem I see is that `table` plugin wouldn't match that design. It's because `table` plugin parses (returns) multiple fields. It means we may need two APIs for plugins then (which is not a problem for me - I'm just making it clear).

### Extend existing `lines` syntax
Current syntax for `lines` looks like this:
```
lines:
  start: ...
  end: ...
  line: ...
```
We could extend it to support following (without breaking backward compatibility):
```
lines:
  - items:
      start: ...
      end: ...
      line: ...
  - rates:
      start: ...
      end: ...
      line: ...
```
