### ISSUE TITLE
Idea: allow "fields" entries to use extended syntax with associative arrays

### ISSUE THREAD

**Issue by rmilecki** [invoice-x/invoice2data#307]
Right now `fields` allows specifying:
1. Regex to use for extracting field data (e.g. `foo: Order (\d+)`)
2. Static value (e.g. `static_bar: Baz`)
3. Sums (e.g. `sum_amount_qux: ...`)

I find current syntax (described above) is a bit loose, limiting and not allowing some further clean development. For example you can't have field starting with `static` using regex (e.g. `static_ip_address: (\d+\.\d+\.\d+\.\d+)`). You can't add new feature like converting extracted value (where to put info how to proceed?).

I'd like to suggest extending `fields` format to support syntax like:
```
fields:
  foo:
    regex: Order (\d+)
  bar:
    static: 'Baz'
  qux:
    sum: ...
```
This would allow specifying field extraction explicitly.

It would also allow adding new features cleanly, things like:
```
fields:
  phone:
    regex: Phone ([\d-]+)
    sub:
      pattern: '-'
      replace: ''
```
Any opinions on this idea?
