### ISSUE TITLE
How to parse long lines?

### ISSUE THREAD

**Issue by sergiuturus** [invoice-x/invoice2data#360]
I'm using the lines feature to extract values from an invoice. It works fine for products having description value on a single row. But there are cases where the description is too long and it takes 2 rows:

```
       Nr.                                                                                                              Unit Price             Value             VAT value
               Description                                                                U.M.        Quantity
       crt                                                                                                          (without VAT) -Lei-            -Lei-                -Lei-
    
               (LD7010) Jucarie din lemn pentru bebelusi - Cilindru
       33                                                                                 buc                 3                19.00            57.00                10.83
               cu bila - Ocean Blue - Little Dutch
    
       Issued by: John Doe   

                    
```

As you can imagine, the parser fails to extract product's description because there's nothing on the right row (the one having other values like U.M, unit price, value, etc):

`ignoring *        (LD7010) Jucarie din lemn pentru bebelusi - Cilindru* because it doesn't match anything`

`ignoring *        cu bila - Ocean Blue - Little Dutch* because it doesn't match anything`

Settings:

```
lines:
  start: \(without VAT\)
  end: Issued by
  line: (?P<crt>\d+)\s+(?P<description>(?:(?:[a-z0-9A-Z\-\/()])+[ ]{1})+)\s+(?P<um>[a-zA-z]*)(?:[ ]*)\s+(?P<quantity>\d+)(?:[ ]*)\s+(?P<unit_value>\d+.\d+)\s+(?P<total_price>\d+.\d+)\s+(?P<total_vat>\d+.\d+)
```

How should I proceed on this manner?
