### ISSUE TITLE
Given the ground truth, how to generate regex from text sequence input

### ISSUE THREAD

**Issue by alexucb** [invoice-x/invoice2data#361]
Hi I am wondering whether there is a solution to automatically generate regex from ground truth and input text.

take apple invoice for example, assuming we don't know the regex for belowing fields but we do know the field value and ocr, how to generate the regex for amount, date and invoice number?

```
# -*- coding: utf-8 -*-
issuer: Apple Distribution International
fields:
  amount: Total\s+Price\s+\(\w+.VAT\)\s+EUR\s+(\d+,\d{2})
  date: Invoice\s+Date\s?:\s+(\d{2}.\d{2}.\d{4})
  invoice_number: Invoice\s+Number\s?:\s+(\w+)
```
