### ISSUE TITLE
Line item extraction - multiple line items exported as single line item

### ISSUE THREAD

**Issue by iedev1** [invoice-x/invoice2data#437]
Thanks for the awesome project!

I have the a template which _almost_ works but the exported JSON has one line_item with 3 values separated by a `\n` character.

I know I'm missing something really simple but can't quite figure it out.

**Expected output:**
```
[
    {
       // ...
        "lines": [
            {
                "amount": "R 16,875.00",
                "camp_name": "NOSSOB REST CAMP",
                "check_in": "26/06/2022",
                "check_out": "01/07/2022",
                "code_summary": "RF4 (RIVER FRONT CHALET): 1",
                "nights": "5",
                "quantity": "1"
            },
            {
                "amount": "R 11,000.00",
                "camp_name": "NOSSOB REST CAMP",
                "check_in": "26/06/2022",
                "check_out": "01/07/2022",
                "code_summary": "RF2 (RIVER FRONT CHALET):",
                "nights": "5",
                "quantity": "1"
            },
            {
                "amount": "R 6,375.00",
                "camp_name": "BITTERPAN WILDERNESS",
                "check_in": "01/07/2022",
                "check_out": "02/07/2022",
                "code_summary": "RC2 (REED CABIN): 2 single beds, 4x4",
                "nights": "1",
                "quantity": "3"
            }
        ]
    }
]
```

**Actual output:**
```
[
    {
// ...
"lines": [
            {
                "amount": "R 16,875.00\nR 11,000.00\nR 6,375.00",
                "camp_name": "NOSSOB REST CAMP\nNOSSOB REST CAMP\nBITTERPAN WILDERNESS",
                "check_in": "26/06/2022\n26/06/2022\n01/07/2022",
                "check_out": "01/07/2022\n01/07/2022\n02/07/2022",
                "code_summary": "RF4 (RIVER FRONT CHALET): 1\nRF2 (RIVER FRONT CHALET):\nRC2 (REED CABIN): 2 single beds, 4x4",
                "nights": "5\n5\n1",
                "quantity": "1\n1\n3"
            }
        ]
  }
]
```

**The template I'm using:**

```
# -*- coding: utf-8 -*-
issuer: SANParks
fields:
  amount: Total Charges :.*\$(\d+\.\d+)
  date: Original Reservation Date :\s?(\d{2}\/\d{2}\/\d{4})
  invoice_number: Reservation No:\s+([A-Z]\d+)
  #amount_untaxed: TOTAL AMOUNT DUE ON.*\$(\d+\.\d+)
  client_code: Client Code:\s(\d+)
lines:
    start: "Reservation details are as follows :"
    end: "TARIFFS ARE SUBJECT TO ALTERATION WITHOUT ADVANCE NOTICE"
    first_line: ^\s{1,3}Camps.+Amount
    line: \s+?(?P<camp_name>.+)\s+(?P<quantity>\d{1,3})\s+(?P<code_summary>.+:\s.+)\s+(?P<nights>\d{1,3})\s+(?P<check_in>\d{2}\/\d{2}\/\d{4})\s+(?P<check_out>\d{2}\/\d{2}\/\d{4})\s+(\d)\s+(\d)\s+(?P<amount>R \s?\d{1,4},?\d{1,4}.\d{2})
options:
  remove_whitespace: false
  currency: ZAR
  date_formats:
    - '%d/%m/%Y'
  languages:
    - en
  decimal_separator: '.'
```
