### ISSUE TITLE
Could not parse multiline columns 

### ISSUE THREAD

**Issue by zanpk** [invoice-x/invoice2data#454]
Recently I have started using this amazing library. It works well but unfortunately I could not fetch multiline columns.
Is there any support available to fetch multiline columns ?

I have attached sample invoice format kindly [visit this link](https://docdro.id/Tm6wXzM),
my sample template code
```
items_info:
    parser: lines
    start: 'Quantity\s+Product Code\s+Description\s+Price\s+Total'
    end: '\s+Total'
    first_line: (?P<quantity>\d+)\s+(?P<item_code>\w+)\s+(?P<desc>.+)\s+(?P<price>\d+)\s+(?P<amount>\d+))
    line: (?P<description>.+)
```
