### ISSUE TITLE
ValueError on  regex with NoneType in Group Min/Max construct

### ISSUE THREAD

**Issue by bosd** [invoice-x/invoice2data#496]
With the regex parser create a group contstruct:

template:
```
fields:
  date:
    parser: regex
    regex:
      - Date\s+(\d{1,2}-\d{2}-\d{4}\s+\d{2}.\d{2}.\d{2})
      - Date\s+(\d{1,2}-\d{2}-\d{4})
    type: date
    group: max
```
The used pdf file is OCR'd. Sometimes the first regex contains a value, but cannot be converted to a `datetime` type.
dateparser then returns a `NoneType`
example: `30-06-2022 17 52:22` (Conversion fails due to missing colon)

This results in an error on the max function: 
`'>' not supported between instances of 'datetime.datetime' and 'NoneType'`

Desired result:
Return the datetime, in case of dateparsed result. Otherwise only return date
