### ISSUE TITLE
No template for invoices/invoice.pdf

### ISSUE THREAD

**Issue by ayushmankumar7** [invoice-x/invoice2data#510]
Output Screen : 
![image](https://github.com/invoice-x/invoice2data/assets/41910134/fccaaa8a-0fe4-437e-93d5-bb4036bb27e3)

Code: 
```
from invoice2data import extract_data 
from invoice2data.extract.loader import read_templates

templates = read_templates('Template/')
print(templates)
result = extract_data('invoices/invoice.pdf', templates=templates)
print(result)

```

I cannot understand why am i getting this error. 

Sample template: 

```
issuer: MAA TARA FOODS
keywords: 
  - MAA TARA FOODS
  - One More Bakery 

fields: 
  invoice_number: Invoice No:\s+(\w{3})\/\d+\-\d+\/\d+
  invoice_date: Invoice Date:\s+\d+\/\d+\/\d+
  vehicle_number: Vehicle No:\s+(.*)
options:
  remove_whitespace: false 
  currency: INR
  date_formats:
    - '%d/%m/%Y'
  language:
    -en 
  

```
