### ISSUE TITLE
ERROR:root: No template for Invoice.pdf

### ISSUE THREAD

**Issue by nozprod** [invoice-x/invoice2data#512]
Hey,

Always getting the same error, tried both custom and predefined templates (using a french Google bill as example). 

Any idea ?

My template : 
```
issuer: Google Commerce Limited
fields:
  date: Récapitulatif pour la période suivante\s+:\s+(\d{1,2}\s+\w+\.\s+\d{4})
  ttc: Total en EUR\s+([\d,]+) €
  ht: Sous-total en EUR\s+([\d,]+) €
  tva_rate: TVA \((\d{1,3})%\)
  tva_amount: TVA \(\d{1,3}%\)\s+([\d,]+) €
keywords:
  - Google Commerce Limited
  - IE9825613N
options:
  currency: EUR
  date_formats:
    - '%d .%b .%Y'
  languages:
    - fr
  decimal_separator: ','
```

An example bill is attached
[Invoice.pdf](https://github.com/invoice-x/invoice2data/files/11464824/Invoice.pdf)
