### ISSUE TITLE
How to fix "Missing mandatory 'keywords' field" error?

### ISSUE THREAD

**Issue by JustForCodin** [invoice-x/invoice2data#514]
I'm trying to parse my invoice with custom template:
```
issuer: McDonalds
keywords:
- McDonalds
fields:
  total: Total*\$(\d+\.\d+)
  subtotal: Subtotal*\$(\d+\.\d+)
  date: Invoice Date:\s+([a-zA-Z]+ \d+ , \d+)
  due_date: Due Date:\s+([a-zA-Z]+ \d+ , \d+)
  invoice_number: Invoice\s+(\d+) Invoice:\s+(\d+)
  partner_name: Restaurant
options:
  remove_whitespace: false
  currency: USD
  date_formats:
    - '%d/%m/%Y'
lines:
    start: Qty
    end: \* Subtotal
    line: (.*)\$(\d+\.\d+)
```

In my script I call the library:

```
from invoice2data import extract_data
from invoice2data.extract.loader import read_templates

templates = read_templates('templates')
result = extract_data('invoices/invoice45Test.pdf', templates=templates)
print("\n")
print(result)
```

And I'm getting an error: 

```
WARNING:invoice2data.extract.loader: json Loader Failed to load invoice_template.yaml template:
Expecting value: line 1 column 1 (char 0)
WARNING:invoice2data.extract.loader: Failed to load template invoice_template.yaml Missing mandatory 'keywords' field.
ERROR:root: No template for invoices/invoice45Test.pdf
```

Any ideas? :)
