### ISSUE TITLE
Probably issue with text parser

### ISSUE THREAD

**Issue by LK511** [invoice-x/invoice2data#546]
I have following text file invoice.txt and yaml template config. I am receiving following error using command:
invoice2data -t ../plyn --exclude-built-in-templates --input-reader text invoice.txt

command returns:
> ERROR:ocrmypdf._pipeline: cannot identify image file 'output.txt'
> CRITICAL:root: Invoice2data failed to process output.txt
> Error message:

content in invoice.txt:
> PP 
> 
> o 1234 654 3399
> 3 JŠ Faktura - daňový doklad:
> 
> 1234567890 Část A
> 
> ČÍSLO ZÁKAZNÍKA: 0134567813
> 
> Č. SMLUVNÍHO ÚČTU: 0000225454458
> ZŮČTOVACÍ KATEGORIE: MALOODBĚRATEL
> Zákaznická linka: 267 175 333, Zákaznický portál: moje.ppas.cz
> 
> Fakturační adresa Doručovací adresa
>  
> Mateřská škola AAA, BBB CCC, DDD 123
> EEEEEE 654/ 11
> 
> IČ: 12345678 DIČ: CZ987654321
> Číslo účtu: 000000-00012345621568/0900
>  
> ZÚČTOVACÍ OBDOBÍ
> 15.01.2023 - 01.10.2023
> 
> Datum uskuteč. zdan. plnění: 11.11.2023
> Datum vystavení: 11.11.2023
> Datum splatnosti: 11.12.2023
> Platbu ize provést pomocí OR kódu. Vyfofte OR kód Vaším chytrým telefonem prostřednictvím bankovní
> aplikace a nebo naskenujte na bankomatu či platbomatu České spořitelny, a.s., a automaticky se Vám
> předvypiní příkaz k úhradě včetně částky, čísla účtu a variabilního symbolu.
>  
> STRUČNÁ REKAPITULACE VYÚČTOVÁNÍ: ROZLOŽENÍ CENY
>  
> 
> Cena celkem bez DPH: 12 345,67 Kč
> Cena celkem vč. DPH: 23 456,78 Kč DODÁVKA PLYNU 20 123,45 Kč
> Celkem zahrnuté úhrady (zálohy vě. DPH, DISTRIBUCE PLYNU 5.444,14 Kč
> bonusy, přeplatky do záloh, přeplatky/ 12 500,00 Kč E „EOBD
> nedoplatky do 100 Kč) OSTATNÍ 112,22 Kč
> Nedoplatek 12 357,91 Kč
> *Detailní rozpis naleznete v Daňové rekapitulaci v Části B faktury Dodávka plynu: částka za spotřebovaný plyn vč.DPH
> I. fóra pře ášné Ostatní: poplatky a da z plynu uvedeny v část 6 fak
> : . fére přeubéžné řídící s P
> HISTORIE SPOTŘEBY kontr.:jy dle 5 14 (3 Příště bez papíru, ať šetříme přírodu
> v MWh vyhlášky 416 /2004 Sb “ Elektronickou fakturaci si nastavíte v zákaznickém portále na
> v moje.ppas.cz v části zálohy a faktury. Zatím ho nevyužíváte?
> 
> příkazee: Přístup si zařídíte během chvilky a získáte přehled o platbách,
> (— budete moct nahlásit samoodečet nebo změnit výši záloh.
> hlavní účetní: UO. 75
> m
>  
> ; 9-0. BBB 123 ;
> Limitovaný příslib ze dnes IČO: 555 44 6s$ ,
> M
> 

content in folder plyn in file mytemplate.yaml:
```
issuer: PP
keywords:
  - ČÍSLO ZÁKAZNÍKA
  - ZÚČTOVACÍ OBDOBÍ
  - Datum uskuteč. zdan. plnění
  - Datum vystavení
  - Datum splatnosti
  - Cena celkem bez DPH
  - Cena celkem vč. DPH
  - Nedoplatek
  - Přeplatek

fields:
  customer_number: 'ČÍSLO ZÁKAZNÍKA:\s*([\d\s]+)'
  accounting_period: 'ZÚČTOVACÍ OBDOBÍ\s*([\d. -]+ - [\d. -]+)'
  date_of_taxable_supply: 'Datum uskuteč. zdan. plnění:\s*([\d.]+)'
  date_of_issue: 'Datum vystavení:\s*([\d.]+)'
  due_date: 'Datum splatnosti:\s*([\d.]+)'
  total_excluding_vat: 'Cena celkem bez DPH:\s*([\d,. ]+)\s*Kč'
  total_including_vat: 'Cena celkem vč. DPH:\s*([\d,. ]+)\s*Kč'
  underpayment: 'Nedoplatek:\s*([\d,. ]+)\s*Kč'
  overpayment: 'Přeplatek:\s*([\d,. ]+)\s*Kč'
```
