### ISSUE TITLE
Incorrect documentation for `required_fields` option

### ISSUE THREAD

**Issue by flowrean** [invoice-x/invoice2data#577]
In TUTORIAL.md, `required_fields` is listed as an option, nested below the `options` key. I couldn't get this to work so I looked into the code and it seems `required_fields` should actually be at the same level as `options`. Is the documentation erroneous or should the code be changed to match what the docs say?

**Comment by bosd** [comment]
Which section are you referring to?

It is listed as "optional'.

In the section of simple invoice template there is an example.

issuer: Microsoft Regional Sales Corporation
keywords:
- Microsoft
- M9-0002526-N
exclude_keywords:
- Already\s+paid
- Do not pay
fields:
  amount: GrandTotal(\d+\.\d+)HKD
  date: DocumentDate:(\d{1,2}\/\d{1,2}\/\d{4})
  invoice_number: InvoiceNo.:(\w+)
options:
  remove_whitespace: true
  currency: HKD

**Comment by flowrean** [comment]
I am referring to the [Options](https://github.com/invoice-x/invoice2data/blob/master/docs/tutorial.md#options) section (under Template Structure).

The example you give does not use `required_fields`, so I don't think it is relevant in this issue. The documentation suggests that the following should be a valid template:
```yaml
issuer: Microsoft Regional Sales Corporation
keywords:
- Microsoft
- M9-0002526-N
exclude_keywords:
- Already\s+paid
- Do not pay
fields:
  amount: GrandTotal(\d+\.\d+)HKD
  date: DocumentDate:(\d{1,2}\/\d{1,2}\/\d{4})
  invoice_number: InvoiceNo.:(\w+)
options:
  remove_whitespace: true
  currency: HKD
  required_fields:
    - invoice_number
```
However, I can't get it to work like this. Instead, the correct version seems to be:
```yaml
issuer: Microsoft Regional Sales Corporation
keywords:
- Microsoft
- M9-0002526-N
exclude_keywords:
- Already\s+paid
- Do not pay
fields:
  amount: GrandTotal(\d+\.\d+)HKD
  date: DocumentDate:(\d{1,2}\/\d{1,2}\/\d{4})
  invoice_number: InvoiceNo.:(\w+)
options:
  remove_whitespace: true
  currency: HKD
required_fields:
  - invoice_number
```
To reflect this, I think the info about required fields should be in its own section and not under Options. Or at least it should be clarified that it is not be nested under `options` in the template.
