### ISSUE TITLE
Extract lines when one of the fields spans on multiple lines (Alibaba)

### ISSUE THREAD

**Issue by estebanthi** [invoice-x/invoice2data#624]
I have text data like this example:

```txt
For Switch Pro Wireless Controller for

Nintendo Switch Console Wireless                         40. 00              18. 500000          0. 00           20%              2.70                   648. 00                 624. 10

Gamepad

US/EU Wall Charger for DSi AC Adapter

for Nintendo 3DS Power Supply for                      1000. 00               0. 715000          0. 00           20%              0.14                   858. 00                 826. 36

3DSXL
```

As you can see, the item description spans on several lines, while all the rest of the data is part of the middle line. In addition, this is inconsistent because sometimes I will have a description spanning on two lines, and the rest of the data will be part of the second line, and sometimes a description only on a single line and here it works perfectly. Is this possible to parse with invoice2data? With pdfplumber I have no issues because it correctly finds the table, does invoice2data has a way of doing something similar? This is an Alibaba invoice for reference, maybe someone already made a template but I could not find.

For now I have this lines parser, which is working for all fields but the description (I only get the description line on the same line as the rest, which is expected but I can't find a way to make it work as I want):

```yaml
lines:
  parser: lines
  rules:
    - start: ITEMS
      end: Grant Total
      line: (?P<description>.+)\s+(?P<quantity>\d+.\d+)\s+(?P<unit_price>\d+.\d+)\s+(?P<discount>\d+.\d+)\s+(?P<tax_rate>\d+%)\s+(?P<tax>\d+.\d+)\s+(?P<amount_usd>\d+.\d+)\s+(?P<amount_eur>\d+.\d+)
```

**Comment by bosd** [comment]
Yes, this is doable. The `lines` parser only starts collecting `line`/`last_line` rows **after** it matches `first_line`, so the trick for "description spread around the data row" is to bracket each item with `first_line` … `last_line` and let the description accumulate.

For your Alibaba layout (description on its own lines, all numbers on one line), make the **numbers line** the `last_line` and a description line the `first_line`:

```yaml
lines:
  parser: lines
  rules:
    - start: ITEMS
      end: Grant Total
      first_line: '^(?P<description>\D+?)$'         # a text-only line starts an item
      line: '^(?P<description>\D+?)$'               # additional description lines
      last_line: '(?P<quantity>\d+\.\s*\d+)\s+(?P<unit_price>\d+\.\s*\d+)\s+(?P<discount>\d+\.\s*\d+)\s+(?P<tax_rate>\d+%)\s+(?P<tax>\d+\.\d+)\s+(?P<amount_usd>\d+\.\d+)\s+(?P<amount_eur>\d+\.\d+)'
```

Same-named capture groups (here `description`) on `first_line`/`line` are joined with `\n` automatically, so multi-line descriptions get concatenated; the `last_line` (the numbers row) closes the item. Note your sample has spaces *inside* the numbers (`40. 00`, `18. 500000`), hence `\d+\.\s*\d+`.

Since you said pdfplumber already finds the table cleanly, `--input-reader pdfplumber` + this rule is your best bet. Docs for `first_line`/`last_line`/`skip_line`: https://invoice2data.readthedocs.io/latest/tutorial.html

The regex above is a starting point (I can't test it against your PDF) — if a `--debug` dump still won't parse, paste it and I'll help tune it. Closing as answered; reopen anytime.
